services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always # Ensures the database restarts if it crashes

  mongo-restore:
    image: mongo:latest
    container_name: mongorestore
    volumes:
      - ./mongo_backup:/data/backup
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for MongoDB to be ready..."
        until mongosh --host mongo --eval "db.runCommand({ ping: 1 })"; do
          sleep 2
        done
        echo "MongoDB is ready. Starting restore..."
        mongorestore --host mongo --db flash_tron /data/backup/flash_tron
    depends_on:
      - mongo


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/flash_tron
    command: npm run dev # Enables hot reloading
    develop:
      watch: # Track live changes during development
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    command: npm start # Enables live updates
    develop:
      watch:  # Track live changes during development
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
